# Metrics (MSE, MAE, confusion matrix)

### Confusion Matrix

- to know the performance of CLASSIFICATION
- comparision beetween ACTUAL and PREDICTED values
- matrix number of rows and columns depends of NUMBER OF CLASSES

In [16]:
# Creation of confusion matrix in using sklearn
from sklearn.metrics import confusion_matrix

#Let actual value be 1 for apple and 0 grapes for our example
ACTUAL = [1,1,1,1,1,1,1,1,0,0,0,0,0,0,0]

# Let the predicted values be
PREDICTION= [1,0,0,0,1,1,1,1,0,0,0,0,0,1,1]

# Confusion matrix for actual and predicted values.
matrix = confusion_matrix(ACTUAL,PREDICTION, labels=[1,0])
print('Confusion matrix : n',matrix)

# outcome values order in sklearn
TP, FN, FP, TN = confusion_matrix(ACTUAL,PREDICTION,labels=[1,0]).reshape(-1)
print('Outcome values : n', TP, FN, FP, TN)

Confusion matrix : n [[5 3]
 [2 5]]
Outcome values : n 5 3 2 5


### How to read it?

- we are looking for 4 values, for each class
    - TP, true positive is Actual = Predicted
    - FP, false positive is Actual <> Predicted
    - TN, true negative is Actual of different class = Predicted
    - FN, false negative is Actual of different class <> Predicted

In [15]:
# for wine database

from sklearn.datasets import load_wine
X, y = load_wine()['data'], load_wine()['target']

#spliting data and using a classifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
knn = KNeighborsClassifier(n_neighbors = 8).fit(X_train, y_train)

y_pred = knn.predict(X_test)

#confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[25  0  1]
 [ 2 17  8]
 [ 3 10  6]]


In [18]:
import numpy as np
classes = np.unique(y_train)
print(classes)

[0 1 2]


   0    1   2
<br>0 [[25  0  1]
<br>1 [ 2 17  8]
<br>2 [ 3 10  6]]
 
 ### How to read that?
 
 Let's take class **<font color='red'>0</font>**
 
**TP, true positive is Actual = Predicted**
 
 0 meets 0 -> 25
 
**FP, false positive is Actual <> Predicted**

Row 0 but 1 and 2 in columns -> 0 + 1 = 1

**TN, true negative is Actual of different class = Predicted**

Rows 1 and 2 but 0 in column -> 2 + 3 = 5

**FN, false negative is Actual of different class <> Predicted**

Rows 1 and 2 and columns 1 and 2 -> 17 + 8 + 10 + 6 = 41


In [ ]:

https://www.analyticsvidhya.com/blog/2021/06/confusion-matrix-for-multi-class-classification/