# Metrics (MSE, MAE, confusion matrix)

In [ ]:
sklearn.metrics.mean_squared_error

In [4]:
from sklearn.datasets import load_wine
X, y = load_wine()['data'], load_wine()['target']

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
knn = KNeighborsClassifier(n_neighbors = 8).fit(X_train, y_train)

y_pred = knn.predict(X_test)


from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))






[[25  0  1]
 [ 2 17  8]
 [ 3 10  6]]


In [ ]:
https://www.analyticsvidhya.com/blog/2021/06/confusion-matrix-for-multi-class-classification/

In [ ]:
Why  Confusion matrix?

Confusion Matrix allows us to measure Recall, Precision,
Accuracy and AUC-ROC curve are the metrics to measure the performance of
the model.

In [10]:
import numpy as np
classes = np.unique(y_train)
print(classes)

[0 1 2]


In [15]:
TP, FN, FP, TN = confusion_matrix(y_test,y_pred,labels=[1,0]).reshape(-1)
print('Outcome values : n', TP, FN, FP, TN)

Outcome values : n 17 2 0 25


In [19]:
list(load_wine().target_names)

['class_0', 'class_1', 'class_2']